version: "3.1"

services:
  php:
    build: .
    working_dir: /app
    volumes:
    - ./:/app
  composer:
    image: composer/composer:2.1.2
    working_dir: /app
    entrypoint: composer
    volumes:
    - ./:/app
