<?php

declare(strict_types=1);

namespace GSSC\Routes\Providers;

class ServiceProvider extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
